# Generated by Django 3.1.12 on 2025-03-23 23:38

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20250323_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
    ]
