# Generated by Django 3.1.12 on 2025-03-24 12:02

import bson.objectid
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_auto_20250323_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
    ]
