# Generated by Django 3.1.12 on 2025-03-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20250324_0802'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
