# Generated by Django 3.1.12 on 2025-03-24 13:02

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_auto_20250324_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('books', models.ManyToManyField(blank=True, to='wishlist.Book')),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
    ]
