# Generated by Django 3.1.12 on 2025-03-23 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
