# Generated by Django 4.2.19 on 2025-03-03 21:43

from django.db import migrations
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
